#!/usr/bin/env bash
# Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0

apt-get -y update
apt-get -y install haproxy=2.0.\*

service haproxy start

# Backup
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.Backup 2> /dev/null

# Config
cfg="\n
fronted http_front
    \tbind *:80
    \tmode http
    \tdefault_backend http_back\n

backend http_back
    \tbalance roundrobin
    \toption forwardfor
    \tserver 1639-web-01 35.231.223.17 check
    \tserver 1639-web-02 34.75.203.83 check\n
"

echo -e "$cfg" >> /etc/haproxy/haproxy.cfg

service haproxy restart
