#!/usr/bin/env bash
# Bash script that:
#Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

FILE="/var/run/holbertonscript.pid"
sudo touch $FILE
sudo echo $$ > $FILE

while true
do
    trap 'echo "I hate the kill command"; sudo rm $FILE' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm $FILE' SIGQUIT
    echo "To infinity and beyond"
    sleep 2
done
