#!/usr/bin/env bash
# 
FILE="/var/run/my_process.pid"
OPT=$1

create_file()
{
    sudo touch $FILE
    sudo bash -c "echo $$ > $FILE"
}

kill_pid()
{
    kill "$(pgrep -a -x bash | grep ./101-manage_my_process | cut -d' ' -f1)"
}

if [ "$OPT" == "start" ]; then
    create_file
    ./manage_my_process &
    echo "manage_my_process started"

elif [ "$OPT" == "restart" ]; then
    sudo rm $FILE
    create_file
    ./manage_my_process &
    echo "manage_my_process restarted"

elif [ "$OPT" == "stop" ]; then
    sudo rm $FILE
    echo "manage_my_process stopped"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
