#!/usr/bin/env bash
# Bash script that displays Fizz Buzz in numbers from 1 to 100.

words[3]=Fizz
words[5]=Buzz
for i in {1..100}; do
	output=""
	for index in "${!words[@]}"; do
		if ((i % index == 0 )); then output+="${words[$index]}"; fi
	done  
	if [ -z $output ]; then output=$i; fi
	echo $output
done
