#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

# cript should only display:
# username
# user id
# Home directory path for the user

while read p; do
	echo "$p" | cut -d':' -f1,3,6
done < /etc/passwd
