#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code from apache-access.log

awk -F' ' '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -nr | sed 's/ */    /'
