#!/usr/bin/env bash
# script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations

COUNT=0
while [ $COUNT -lt 10 ]; do
    if [ "$COUNT" == 3 ]; then
        echo bad luck
    elif [ "$COUNT" == 7 ]; then
        echo good luck
    else
        echo Holberton School
    fi
    let COUNT=COUNT+1 
done
