#!/usr/bin/env bash
# Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

for i in $( find . | cut -d'-' -f2  | tr -d './' ); do
    echo "$i"
done