#!/usr/bin/env bash
# Install an configure firewall
sudo apt install ufw​​​2
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
sudo ufw status verbose
