#!/usr/bin/env bash
# change local ip's >> file /etc/hosts
cp /etc/hosts /tmp/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /tmp/hosts.new
echo -e '8.8.8.8 facebook.com' >> /tmp/hosts.new
cp -f /tmp/hosts.new /etc/hosts
